---
apiVersion: v1
kind: Secret
metadata:
  name: bukalapak-registry
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
  labels:
    ingress-type: {{ $.Values.ingress.type }}
    type: secret
    {{- include "nginx-ingress.mandatoryMetadataLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "Image registry pull secrets not defined !!!" $.Values.image.pullSecrets }}
