---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.name }}-{{ $.Values.cluster }}-serviceaccount
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
  labels:
    ingress-type: {{ $.Values.ingress.type }}
    type: serviceaccount
    {{- include "nginx-ingress.mandatoryMetadataLabels" . | nindent 4 }}