---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Values.project }}-{{ $.Values.environment }}-admin-rolebinding
  namespace: {{ $.Values.project }}
  labels:
    type: rolebinding
    {{- include "namespace-rbac.mandatoryMetadataLabels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ $.Values.project }}-{{ $.Values.environment }}-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- range $name,$id := $.Values.groupID }}
- kind: Group
  name: {{ $id }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
- kind: ServiceAccount
  name: {{ $.Values.project }}-{{ $.Values.environment }}-serviceaccount
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
