---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Values.project }}-{{ $.Values.environment }}-admin
  namespace: {{ $.Values.project }}
  labels:
    type: role
    {{- include "namespace-rbac.mandatoryMetadataLabels" . | nindent 4 }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
