---
# Create Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.project }}-{{ $.Values.environment }}-serviceaccount
  namespace: {{ $.Values.project }}
  labels:
    type: serviceaccount
  {{- include "namespace-rbac.mandatoryMetadataLabels" . | nindent 4 }}

---
# Create token associated with Service Account above
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.project }}-{{ $.Values.environment }}-serviceaccount-token
  namespace: {{ $.Values.project }}
  annotations:
    kubernetes.io/service-account.name: {{ $.Values.project }}-{{ $.Values.environment }}-serviceaccount
  labels:
    type: secret
    {{- include "namespace-rbac.mandatoryMetadataLabels" . | nindent 4 }}
type: kubernetes.io/service-account-token
